version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379" # Expose Redis port
    networks:
      - limiter-net
    volumes:
      - redis_data:/data # Persist Redis data

  api:
    build: .
    ports:
      - "3000:3000" # Expose API port
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RATE_LIMIT=100
      - WINDOW_SECONDS=60
    depends_on:
      - redis
    networks:
      - limiter-net

networks:
  limiter-net:

volumes:
  redis_data:
